services:
  postgres:
    image: postgres:18-alpine
    container_name: solaire-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: solaire
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d solaire"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
